services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  cds.owncloud.tools:
    class: MeloFlavio\OwncloudUploaderBundle\Storage\OwnCloudTools

  cds.owncloud_storage:
    class : MeloFlavio\OwncloudUploaderBundle\Storage\OwnCloudStorage
    arguments: [ '@vich_uploader.property_mapping_factory', '@cds.owncloud.tools']
